"""
Shared data models for the 9-stage Logistics & Procurement pipeline.

Every stage reads from and writes to these structures.
They are plain dataclasses (no ORM) — the API layer handles DB persistence.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from enum import Enum
from typing import Any, Optional


# ─── Enums ───────────────────────────────────────────────────────────────────


class SupplyChainType(str, Enum):
    OVERSEAS = "overseas"    # Profile A: 6–14 week lead time, ocean freight
    DOMESTIC = "domestic"    # Profile B: same-day to 2 weeks


class UrgencyLevel(str, Enum):
    GREEN = "green"    # reorder within 2 weeks is fine
    YELLOW = "yellow"  # reorder this week
    RED = "red"        # reorder immediately — stockout risk


class ProcurementStage(str, Enum):
    DEMAND_MONITORING = "1_demand_monitoring"
    PO_GENERATION = "2_po_generation"
    VENDOR_RESPONSE = "3_vendor_response"
    FREIGHT_BOOKING = "4_freight_booking"
    IN_TRANSIT = "5_in_transit"
    AT_PORT = "6_at_port"
    CUSTOMS_CLEARANCE = "6b_customs_clearance"
    DRAYAGE = "7_drayage"
    WAREHOUSE_RECEIPT = "7b_warehouse_receipt"
    COST_RECONCILIATION = "8_cost_reconciliation"
    COMPLETE = "9_complete"


class CycleStatus(str, Enum):
    OPEN = "open"
    ON_TRACK = "on_track"
    DELAYED = "delayed"
    NEEDS_ATTENTION = "needs_attention"
    COMPLETE = "complete"
    CANCELLED = "cancelled"


class CommunicationDirection(str, Enum):
    OUTBOUND = "outbound"
    INBOUND = "inbound"


# ─── SKU Profile ──────────────────────────────────────────────────────────────


@dataclass
class SKUProfile:
    """
    Supply chain profile for a single SKU.
    This is the master configuration that drives all pipeline logic for this SKU.
    """
    sku: str
    name: str
    supplier_id: str
    supplier_name: str
    supply_chain_type: SupplyChainType
    origin_country: str = ""
    origin_port: str = ""
    destination_port: str = ""
    hs_code: str = ""

    # Service level target: A=0.97, B=0.93, C=0.88
    service_level_target: float = 0.95
    sku_tier: str = "B"   # A | B | C

    # Cost
    unit_cost_fob: float = 0.0           # FOB cost per unit
    cases_per_pallet: int = 60
    cases_per_20ft_container: int = 800
    cases_per_40ft_container: int = 1_600
    cases_per_40hc_container: int = 1_800
    minimum_order_cases: int = 0

    # Current stock state (updated from QB sync)
    stock_on_hand: int = 0
    stock_committed: int = 0            # allocated to open orders
    stock_in_transit: int = 0           # already on order / in transit

    def to_dict(self) -> dict:
        return {
            "sku": self.sku,
            "name": self.name,
            "supplier_id": self.supplier_id,
            "supplier_name": self.supplier_name,
            "supply_chain_type": self.supply_chain_type.value,
            "origin_country": self.origin_country,
            "service_level_target": self.service_level_target,
            "sku_tier": self.sku_tier,
            "unit_cost_fob": self.unit_cost_fob,
            "stock_on_hand": self.stock_on_hand,
            "stock_committed": self.stock_committed,
            "stock_in_transit": self.stock_in_transit,
        }


# ─── Stage 1: Reorder Decision Package ───────────────────────────────────────


@dataclass
class DemandProjection:
    """14-week forward demand projection with confidence range."""
    weekly_demand: list[float]          # 14 values
    weekly_demand_low: list[float]      # lower bound (10th percentile)
    weekly_demand_high: list[float]     # upper bound (90th percentile)
    seasonal_adjustment_applied: bool = False
    confidence: float = 0.7

    @property
    def total_14_week(self) -> float:
        return sum(self.weekly_demand)

    @property
    def avg_weekly(self) -> float:
        return self.total_14_week / 14 if self.weekly_demand else 0.0


@dataclass
class ReorderDecisionPackage:
    """
    Complete reorder decision package generated by Stage 1.
    Contains everything the logistics manager needs to act.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    sku_profile: Optional[SKUProfile] = None
    urgency: UrgencyLevel = UrgencyLevel.GREEN

    # Current position
    net_available: int = 0              # on_hand - committed + in_transit
    days_of_supply: float = 0.0
    projected_stockout_date: Optional[str] = None

    # Demand
    demand_projection: Optional[DemandProjection] = None
    avg_daily_demand: float = 0.0

    # Recommended order
    recommended_qty: int = 0
    recommended_qty_reasoning: str = ""
    container_fill_pct: float = 0.0    # how full the container would be
    container_suggestion: str = ""     # upsell suggestion if < 80%

    # Lead time
    expected_lead_time_days: float = 0.0
    lead_time_p80_days: float = 0.0    # 80th percentile (planning lead time)

    # Cost estimate
    estimated_fob_cost: float = 0.0
    estimated_freight_cost: float = 0.0
    estimated_landed_cost: float = 0.0
    last_order_reference: str = ""
    price_change_flag: bool = False
    price_change_note: str = ""

    # Resolution
    approved: bool = False
    approved_qty: Optional[int] = None
    approved_by: str = ""
    dismissed: bool = False
    dismiss_reason: str = ""

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "created_at": self.created_at,
            "sku": self.sku_profile.sku if self.sku_profile else None,
            "sku_name": self.sku_profile.name if self.sku_profile else None,
            "supplier": self.sku_profile.supplier_name if self.sku_profile else None,
            "supply_chain_type": self.sku_profile.supply_chain_type.value if self.sku_profile else None,
            "urgency": self.urgency.value,
            "net_available": self.net_available,
            "days_of_supply": round(self.days_of_supply, 1),
            "projected_stockout_date": self.projected_stockout_date,
            "avg_daily_demand": round(self.avg_daily_demand, 2),
            "recommended_qty": self.recommended_qty,
            "recommended_qty_reasoning": self.recommended_qty_reasoning,
            "container_fill_pct": round(self.container_fill_pct, 1),
            "container_suggestion": self.container_suggestion,
            "expected_lead_time_days": round(self.expected_lead_time_days, 0),
            "estimated_landed_cost": round(self.estimated_landed_cost, 2),
            "price_change_flag": self.price_change_flag,
            "price_change_note": self.price_change_note,
            "approved": self.approved,
            "dismissed": self.dismissed,
        }


# ─── Stage 2: Purchase Order ──────────────────────────────────────────────────


@dataclass
class POLineItem:
    sku: str
    description: str
    qty_cases: int
    unit_price: float
    total_price: float
    hs_code: str = ""
    notes: str = ""

    def to_dict(self) -> dict:
        return {
            "sku": self.sku,
            "description": self.description,
            "qty_cases": self.qty_cases,
            "unit_price": round(self.unit_price, 4),
            "total_price": round(self.total_price, 2),
            "hs_code": self.hs_code,
            "notes": self.notes,
        }


@dataclass
class PurchaseOrder:
    po_number: str
    supplier_id: str
    supplier_name: str
    supplier_email: str
    ship_to_address: str
    payment_terms: str
    requested_ship_date: str
    language: str = "en"   # "en" | "es" | "fr"
    line_items: list[POLineItem] = field(default_factory=list)
    special_instructions: str = ""
    status: str = "draft"  # draft | sent | confirmed | partially_confirmed | cancelled

    # Populated after confirmation
    confirmed_ship_date: Optional[str] = None
    confirmed_eta: Optional[str] = None
    supplier_ref: str = ""

    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    sent_at: Optional[str] = None
    confirmed_at: Optional[str] = None

    @property
    def total_value(self) -> float:
        return sum(li.total_price for li in self.line_items)

    @property
    def total_cases(self) -> int:
        return sum(li.qty_cases for li in self.line_items)

    def to_dict(self) -> dict:
        return {
            "po_number": self.po_number,
            "supplier_id": self.supplier_id,
            "supplier_name": self.supplier_name,
            "status": self.status,
            "line_items": [li.to_dict() for li in self.line_items],
            "total_value": round(self.total_value, 2),
            "total_cases": self.total_cases,
            "payment_terms": self.payment_terms,
            "requested_ship_date": self.requested_ship_date,
            "confirmed_ship_date": self.confirmed_ship_date,
            "confirmed_eta": self.confirmed_eta,
            "created_at": self.created_at,
            "sent_at": self.sent_at,
        }


# ─── Stage 3: Vendor Communication ───────────────────────────────────────────


@dataclass
class VendorCommunication:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    po_number: str = ""
    direction: CommunicationDirection = CommunicationDirection.OUTBOUND
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    subject: str = ""
    body_summary: str = ""    # AI-parsed summary
    raw_body: str = ""
    extracted_data: dict = field(default_factory=dict)
    # Extracted fields: confirmed_qty, confirmed_price, eta_ship, eta_arrival, issues

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "po_number": self.po_number,
            "direction": self.direction.value,
            "timestamp": self.timestamp,
            "subject": self.subject,
            "body_summary": self.body_summary,
            "extracted_data": self.extracted_data,
        }


# ─── Stage 4: Freight Booking ─────────────────────────────────────────────────


@dataclass
class FreightCostComponent:
    component: str         # ocean_freight | fuel_surcharge | origin_charges | etc.
    amount_usd: float
    notes: str = ""

    def to_dict(self) -> dict:
        return {"component": self.component, "amount_usd": round(self.amount_usd, 2), "notes": self.notes}


@dataclass
class FreightBooking:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    po_number: str = ""
    booking_ref: str = ""
    vessel_name: str = ""
    voyage_number: str = ""
    bill_of_lading: str = ""
    container_numbers: list[str] = field(default_factory=list)
    container_type: str = "40HC"   # 20GP | 40GP | 40HC | LCL
    origin_port: str = ""
    destination_port: str = ""
    etd: Optional[str] = None      # Estimated Time of Departure (ISO date)
    eta: Optional[str] = None      # Estimated Time of Arrival (ISO date)
    atd: Optional[str] = None      # Actual Time of Departure
    ata: Optional[str] = None      # Actual Time of Arrival
    carrier: str = ""
    forwarder: str = ""
    cost_components: list[FreightCostComponent] = field(default_factory=list)
    status: str = "booked"   # booked | departed | in_transit | arrived | delivered

    @property
    def total_freight_cost(self) -> float:
        return sum(c.amount_usd for c in self.cost_components)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "po_number": self.po_number,
            "booking_ref": self.booking_ref,
            "vessel_name": self.vessel_name,
            "container_numbers": self.container_numbers,
            "container_type": self.container_type,
            "origin_port": self.origin_port,
            "destination_port": self.destination_port,
            "etd": self.etd,
            "eta": self.eta,
            "atd": self.atd,
            "ata": self.ata,
            "carrier": self.carrier,
            "status": self.status,
            "total_freight_cost": round(self.total_freight_cost, 2),
            "cost_components": [c.to_dict() for c in self.cost_components],
        }


# ─── Stage 5: Transit Tracking ────────────────────────────────────────────────


@dataclass
class TrackingEvent:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    booking_id: str = ""
    checked_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    vessel_lat: Optional[float] = None
    vessel_lon: Optional[float] = None
    current_port: str = ""
    status_description: str = ""
    updated_eta: Optional[str] = None
    original_eta: Optional[str] = None
    delay_days: int = 0              # positive = late, negative = early
    inventory_impact: str = ""       # human-readable impact analysis
    mitigation_options: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "booking_id": self.booking_id,
            "checked_at": self.checked_at,
            "position": {"lat": self.vessel_lat, "lon": self.vessel_lon}
            if self.vessel_lat else None,
            "current_port": self.current_port,
            "status": self.status_description,
            "updated_eta": self.updated_eta,
            "delay_days": self.delay_days,
            "inventory_impact": self.inventory_impact,
            "mitigation_options": self.mitigation_options,
        }


# ─── Stage 6: Customs ─────────────────────────────────────────────────────────


@dataclass
class CustomsEvent:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    booking_id: str = ""
    milestone: str = ""    # entry_filed | duties_paid | hold_placed | exam_requested |
    #                         exam_completed | hold_released | released
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    notes: str = ""
    hold_reason: str = ""   # if milestone == hold_placed
    demurrage_accruing: bool = False
    demurrage_rate_per_day: float = 0.0
    demurrage_days: int = 0

    @property
    def demurrage_total(self) -> float:
        return self.demurrage_rate_per_day * self.demurrage_days

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "booking_id": self.booking_id,
            "milestone": self.milestone,
            "timestamp": self.timestamp,
            "notes": self.notes,
            "hold_reason": self.hold_reason,
            "demurrage_total": round(self.demurrage_total, 2) if self.demurrage_accruing else 0,
        }


# ─── Stage 7: Warehouse Receipt ───────────────────────────────────────────────


@dataclass
class ReceiptLineItem:
    sku: str
    qty_ordered: int
    qty_received: int
    qty_short: int
    condition_notes: str = ""

    @property
    def is_complete(self) -> bool:
        return self.qty_received >= self.qty_ordered

    def to_dict(self) -> dict:
        return {
            "sku": self.sku,
            "qty_ordered": self.qty_ordered,
            "qty_received": self.qty_received,
            "qty_short": self.qty_short,
            "condition_notes": self.condition_notes,
            "complete": self.is_complete,
        }


@dataclass
class WarehouseReceipt:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    po_number: str = ""
    booking_id: str = ""
    received_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    received_by: str = ""
    line_items: list[ReceiptLineItem] = field(default_factory=list)
    total_cases_received: int = 0
    condition: str = "good"   # good | partial_damage | full_damage
    notes: str = ""

    # Stage-by-stage lead time log (days)
    po_to_ship_days: Optional[float] = None
    ship_to_arrival_days: Optional[float] = None
    arrival_to_customs_days: Optional[float] = None
    customs_to_warehouse_days: Optional[float] = None
    total_lead_time_days: Optional[float] = None
    predicted_lead_time_days: Optional[float] = None

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "po_number": self.po_number,
            "received_at": self.received_at,
            "line_items": [li.to_dict() for li in self.line_items],
            "total_cases_received": self.total_cases_received,
            "condition": self.condition,
            "lead_time": {
                "po_to_ship_days": self.po_to_ship_days,
                "ship_to_arrival_days": self.ship_to_arrival_days,
                "arrival_to_customs_days": self.arrival_to_customs_days,
                "customs_to_warehouse_days": self.customs_to_warehouse_days,
                "total_days": self.total_lead_time_days,
                "predicted_days": self.predicted_lead_time_days,
            },
        }


# ─── Stage 8: Landed Cost & Variance ─────────────────────────────────────────


@dataclass
class LandedCostBreakdown:
    """Complete landed cost for one shipment, per SKU."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    po_number: str = ""
    sku: str = ""
    cases: int = 0

    # Cost components (per case)
    fob_cost_per_case: float = 0.0
    ocean_freight_per_case: float = 0.0
    fuel_surcharge_per_case: float = 0.0
    origin_charges_per_case: float = 0.0
    insurance_per_case: float = 0.0
    customs_duty_per_case: float = 0.0
    broker_fees_per_case: float = 0.0
    port_charges_per_case: float = 0.0
    demurrage_per_case: float = 0.0
    drayage_per_case: float = 0.0
    exam_fees_per_case: float = 0.0

    shipment_date: str = ""
    supplier_id: str = ""

    @property
    def total_landed_cost_per_case(self) -> float:
        return (
            self.fob_cost_per_case + self.ocean_freight_per_case
            + self.fuel_surcharge_per_case + self.origin_charges_per_case
            + self.insurance_per_case + self.customs_duty_per_case
            + self.broker_fees_per_case + self.port_charges_per_case
            + self.demurrage_per_case + self.drayage_per_case
            + self.exam_fees_per_case
        )

    @property
    def total_shipment_cost(self) -> float:
        return self.total_landed_cost_per_case * self.cases

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "po_number": self.po_number,
            "sku": self.sku,
            "cases": self.cases,
            "cost_per_case": {
                "fob": round(self.fob_cost_per_case, 4),
                "ocean_freight": round(self.ocean_freight_per_case, 4),
                "fuel_surcharge": round(self.fuel_surcharge_per_case, 4),
                "origin_charges": round(self.origin_charges_per_case, 4),
                "insurance": round(self.insurance_per_case, 4),
                "customs_duty": round(self.customs_duty_per_case, 4),
                "broker_fees": round(self.broker_fees_per_case, 4),
                "port_charges": round(self.port_charges_per_case, 4),
                "demurrage": round(self.demurrage_per_case, 4),
                "drayage": round(self.drayage_per_case, 4),
                "exam_fees": round(self.exam_fees_per_case, 4),
                "total": round(self.total_landed_cost_per_case, 4),
            },
            "total_shipment_cost": round(self.total_shipment_cost, 2),
            "shipment_date": self.shipment_date,
        }


@dataclass
class CostVariance:
    """A detected variance between two shipments' landed cost components."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    po_number: str = ""
    sku: str = ""
    component: str = ""          # which cost component changed
    previous_value: float = 0.0
    current_value: float = 0.0
    change_usd: float = 0.0
    change_pct: float = 0.0
    per_case_impact: float = 0.0
    annualized_impact: float = 0.0  # if this persists across future shipments
    severity: str = "info"       # info | warning | alert | critical
    resolved: bool = False
    resolution_note: str = ""
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "po_number": self.po_number,
            "sku": self.sku,
            "component": self.component,
            "previous_value": round(self.previous_value, 4),
            "current_value": round(self.current_value, 4),
            "change_usd": round(self.change_usd, 2),
            "change_pct": round(self.change_pct, 1),
            "per_case_impact": round(self.per_case_impact, 4),
            "annualized_impact": round(self.annualized_impact, 2),
            "severity": self.severity,
            "resolved": self.resolved,
            "created_at": self.created_at,
        }


# ─── Master Procurement Cycle ─────────────────────────────────────────────────


@dataclass
class ProcurementCycle:
    """
    Master record tracking the complete lifecycle of one procurement event
    from reorder trigger through warehouse receipt and cost reconciliation.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    company_id: str = ""
    stage: ProcurementStage = ProcurementStage.DEMAND_MONITORING
    status: CycleStatus = CycleStatus.OPEN
    supply_chain_type: SupplyChainType = SupplyChainType.OVERSEAS
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    # Linked records (populated as cycle progresses)
    reorder_decision: Optional[ReorderDecisionPackage] = None
    purchase_order: Optional[PurchaseOrder] = None
    vendor_communications: list[VendorCommunication] = field(default_factory=list)
    freight_booking: Optional[FreightBooking] = None
    tracking_events: list[TrackingEvent] = field(default_factory=list)
    customs_events: list[CustomsEvent] = field(default_factory=list)
    warehouse_receipt: Optional[WarehouseReceipt] = None
    landed_costs: list[LandedCostBreakdown] = field(default_factory=list)
    cost_variances: list[CostVariance] = field(default_factory=list)

    # Stage timestamps (ISO)
    stage_timestamps: dict[str, str] = field(default_factory=dict)

    def advance_to(self, stage: ProcurementStage) -> None:
        self.stage = stage
        self.updated_at = datetime.now(timezone.utc).isoformat()
        self.stage_timestamps[stage.value] = self.updated_at

    def days_in_current_stage(self) -> float:
        entered = self.stage_timestamps.get(self.stage.value, self.created_at)
        try:
            start = datetime.fromisoformat(entered.replace("Z", "+00:00"))
            delta = datetime.now(timezone.utc) - start
            return delta.total_seconds() / 86400
        except (ValueError, TypeError):
            return 0.0

    @property
    def po_number(self) -> str:
        return self.purchase_order.po_number if self.purchase_order else ""

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "stage": self.stage.value,
            "status": self.status.value,
            "supply_chain_type": self.supply_chain_type.value,
            "po_number": self.po_number,
            "days_in_current_stage": round(self.days_in_current_stage(), 1),
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "stage_timestamps": self.stage_timestamps,
            "has_freight_booking": self.freight_booking is not None,
            "has_receipt": self.warehouse_receipt is not None,
            "cost_variances": len(self.cost_variances),
            "unresolved_variances": sum(1 for v in self.cost_variances if not v.resolved),
        }
